Berksfile
recipes/service_runit.rb
spec/unit/recipes/config_spec.rb
spec/unit/recipes/default_spec.rb
spec/unit/recipes/knife_spec.rb
spec/unit/recipes/linux_spec.rb
spec/unit/recipes/windows_spec.rb

The runit service often fails to start/restart due to timeouts. This
simply extends the number of times we try - since the runit command is
itself idempotent, it should make us much more resiliant aginst
failures.
Also, I updated the test suite to run with the latest ChefDK.
Integration tests are completely non functional, but they appear to
always have been.

Add a retries to the service

---

templates/default/push-jobs-client.rb.erb

On windows systems the /etc/chef/client.rb path doesn't make sense. This attempts to leverage platform_specific_path to do better.
Not necessarily the best at ruby/windows integration, so I'd love feedback. Needs testing before it's mergeable. 
@jtimberman @smurawski

Fix template for windows

---

README.md
attributes/default.rb
metadata.rb
recipes/default.rb
recipes/linux.rb
spec/unit/recipes/linux_spec.rb

Default behavior on Linux is to install from CHEF's public repositories. Setting the package_url and package_checksum attributes overrides that behavior and is still required on Windows.
WARNING:
Chef Push RPM version <= 1.1.5 fails with  `Package opscode-push-jobs-client-1.1.5-1.el6.x86_64.rpm is not signed ` . Future versions of Chef Push will be properly signed.

use chef-ingredient

---

.kitchen.local.yml.example
.kitchen.yml
metadata.rb
test/integration/default/serverspec/localhost/linux_spec.rb
test/integration/default/serverspec/spec_helper.rb

* Chef 12 now requires valid checksums.  I updated the `.kitchen.local.yml.example` to point at the 1.1.5 packages on packagecloud and added valid checksums for all
* we should change this in the future to use chef-ingredient
* Include CentOS 7.1 in the testing matrix
* Fix serverspec tests - all platforms now pass
fixes #22

Add CentOS 7.1 to the test matrix and verify that it works

---

attributes/default.rb
recipes/windows.rb
spec/unit/recipes/windows_spec.rb
templates/default/push-jobs-client.rb.erb

Partially fixes issue #39.
Remaining task is to create the push msi with the path to the config(c:\chef\push-jobs-client.rb) as part of the 'ImagePath' registry entry.

Windows push client to use own config

---

attributes/default.rb
recipes/service_container.rb
recipes/service_runit.rb
templates/default/sv-opscode-push-jobs-client-run.erb

Hi @someara
Currently the logging is hardcoded to debug which I think is due to the addition of the `service_container` recipe.
Unless I'm mistaken, the `service_container` recipe does not pass template variables, so I removed the unused `debug_flag` variable in the recipe.
TLDR:

debug flag to logging level flag

---

Gemfile
attributes/default.rb
recipes/config.rb
templates/default/push-jobs-client.rb.erb

For the purpose of testing we need to be able to disable SSL
checking. This adds an override to allow us to control the two ssl
verification flags 'verify_api_cert' and 'ssl_verify_mode'.
The defaults are set to full verification so this shouldn't break anything.

Add hooks to disable SSL verification

---

attributes/default.rb
recipes/config.rb

It is convenient for some test systems to setup/install the client via chef-solo but have it pointed at a chef & push server instance.

Allow node_name and chef_server_url to be overridden

---

CHANGELOG.md
attributes/default.rb
metadata.rb
recipes/service_windows.rb

This will stop a CCR from restarting the push-jobs service every
$n minutes.

Add a guard to the windows registry updater powershell_script.

---

CHANGELOG.md
libraries/helpers.rb
metadata.rb
spec/spec_helper.rb
spec/support/version-manifest.json
spec/unit/libraries/helpers_spec.rb

Currently if we try to use the `version_from_manifest` method it is
broken, this commit fixes it and adds extra tests to verify
functionality.

Fix version_from_manifest helper method

---

libraries/helpers.rb
spec/unit/helpers_spec.rb

This commit addresses an error that gets raised when trying to
install a non-alpha version of push-client 2.0.0 and above. This
change is necessary for the upcoming push-client release.
An error no longer gets raised when trying to install a non-alpha 
version of push-client 2.0.0 and above.
=====================================================================
Error executing action `create` on resource 'template[/etc/sv/opscode-push-jobs-client/run]'
=====================================================================
Chef::Mixin::Template::TemplateError
------------------------------------
No info for version '2.1.0'
Cookbook Trace:
---------------
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:282:in `block in <class:RunitService>'
Resource Declaration: …

Allow stable versions of >=2.0.0 push-client to be installed

---

metadata.rb
recipes/install.rb

push-jobs should try a compatible package for a platform when it doesn't find an exact match (so install RHEL 6 instead of RHEL 7 if it can't find the RHEL 7 package - in 99% of cases this will just work).
None

Try a compatible package for a non-suported platform

---

.kitchen.docker.yml
.kitchen.yml
metadata.rb

Require a version of runit cookbook that supports RHEL
[List any existing issues this PR resolves]

Avoid potential runit cookbook failures on RHEL

---

resources/service_systemd.rb

There is a typo in the resource that prevents the chef-push-jobs-client systemd service from being enabled to start on boot

Fails to enable systems service to start on boot

---

test/integration/windows/windows_spec.rb

Get a ruby compile error trying to `berks vendor && berks upload`
N/A

Typo preventing berks upload

---

README.md
attributes/default.rb
libraries/helpers.rb
recipes/config.rb

Logs are not generated under /var/log. it seems to require -L option in daemon startup options.
Signed-off-by: akadoya aoi.kadoya@rakops.com

adding log location option

---

attributes/default.rb
metadata.rb

Signed-off-by: Matt Kulka <mkulka@parchment.com>
Sets `node['push_jobs']['logging_dir']` per platform instead of a static Unix path.
Fixes #113

Set logging_dir per platform

---

templates/init_sysv.erb

- Fix installation failure on CentOS 6 because the daemon not started in background
- Fix bash syntax error on line 87
https://github.com/chef-cookbooks/push-jobs/issues/123

Fix issue #123: installation failure on CentOS 6

---

.kitchen.dokken.yml
attributes/default.rb
metadata.rb
recipes/default.rb
resources/service_sysvinit.rb
resources/service_upstart.rb
test/integration/default/linux_spec.rb

This PR adds Amazon Linux support to this cookbook for Chef 13.  On Chef 12, the `platform_family` for that distribution was "rhel", so it worked without modification.
I chose to use Upstart as the init service, as this has been used by Amazon Linux for a number of years.  To make this work, I had to explicitly specify the service provider within `service_upstart.rb` as Chef 13 is selecting the sysvinit provider on that distribution.  This looks a little gross, but should not change behaviour for any other distribution.
I added an Amazon Linux suite to the kitchen-dokken configuration to work through these issues, but I'm not sure whether it's appropriate to add that in this PR as it isn't a supported platform for push-jobs (the contribution guidelines didn't give any hints).
Credit to …

Fix GH-128 - default recipe fails on Amazon Linux with Chef 13

---

resources/service_sysvinit.rb

Signed-off-by: Jeremy J. Miller <jm@chef.io>
Make sysvinit style service default for RHEL/CentOS <= 6
The reality is that there are still some customers who are paying for extended life support of RHEL 5.
This change is a minimum compromise to allow those to use push-jobs cookbook with SysVinit style service.

make sysvinit default for rhel <= 6

---

resources/service_sysvinit.rb
spec/unit/recipes/service_spec.rb

Signed-off-by: Steve Brown <sbrown@chef.io>
Allows installation of push jobs client on sles 11
The commit makes sure that the sysvinit resource is uses for sles 11 systems.
Previously it tried to use the runit service resource, this would fail as the runit cookbook does not support suse.
No issue related to this but it has been requested by a customer
- [ x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ x] New functionality includes testing.
- [ x] New functionality has been documented in the README if applicable
- [ x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

Sles 11 support

---

attributes/default.rb
libraries/helpers.rb
spec/unit/recipes/config_spec.rb
templates/push-jobs-client.rb.erb

This pull adds explicit proxy configuration for push-jobs-client. While undocumented, setting the same
attributes in the config file as chef-client for proxies (e.g. `http_proxy`, `https_proxy`, etc.) does work
for pushy-client. This configuration can be configured via the `node['push_jobs']['proxy']['http']` and
`node['push_jobs']['proxy']['https']` hashes. `node['push_jobs']['no_proxy']` string attribute can also
be specified for which domains/suffixes are to be proxy bypassed.
Fixes #79
Signed-off-by: Matt Kulka <mkulka@parchment.com>

add proxy configuration support

---

recipes/package.rb

Fixes #119
Even when specifying a package via attributes with a version, shasum, and URL, if push jobs is already installed it won't be upgraded. This change will upgrade to the latest version available, which we generally want. Rather than adding a flag to enable upgrades, users can opt-out by specifying a specific package using the existing attributes.

Upgrade the push-jobs client if a newer package is available
